#!/bin/bash

source ../utils/utils.sh

docker-compose down -v
docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
ZOO_1_IP=$(container_to_ip zookeeper-1)
ZOO_2_IP=$(container_to_ip zookeeper-2)
ZOO_3_IP=$(container_to_ip zookeeper-3)
interface=eth0

listTopics() {
	container=$1
	name=$(container_to_name $container)
	shift 1
	bootstrapServers=$1

	docker exec -t $name bash -c "kafka-topics --bootstrap-server $bootstrapServers -list"
}

main() {
	sleep 20
	create_topic zookeeper-1 test 4 3
	sleep 5

	send_message kafka-1 'before network outage'
	read_messages kafka-1 1

	log 'list topics before outage'
	listTopics kafka-1 "kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092"

	log 'Network outage starts'

	# SIMULATE NODES ON DC2 pare Powered off (-> packet loss)
	# rack a
	block_host kafka-1 $KAFKA_3_IP $KAFKA_4_IP
	block_host kafka-2 $KAFKA_3_IP $KAFKA_4_IP
	block_host zookeeper-1 $ZOO_3_IP
	block_host zookeeper-2 $ZOO_3_IP
	# rack B
	block_host kafka-3 $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP $KAFKA_1_IP $KAFKA_2_IP
	block_host kafka-4 $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP $KAFKA_1_IP $KAFKA_2_IP
	block_host zookeeper-3 $ZOO_1_IP $ZOO_2_IP

	log 'list topics after outage'

	for i in {1..10}
	do
	  echo "List topics try $i"
		listTopics kafka-1 "kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092"
	done

	log 'Network outage ends'
	remove_partition kafka-1 kafka-2 kafka-3 kafka-4 zookeeper-1 zookeeper-2 zookeeper-3

	for i in {1..5}
	do
	  echo "List topics try $i"
		listTopics kafka-1 "kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092"
	done
}

main
